site_name: Appunti AESO
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.sections
    - toc.integrate # Enable TOC (auto index)
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Markdown extensions
markdown_extensions:
  - toc:
      baselevel: 2 # Starts ToC from <h2> instead of <h1>
      permalink: "#" # Title linking
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.superfences: # Mermaid support
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true # LaTeX support

# LaTeX support (MathJax)
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.js

extra_css:
  - overrides/main.css

# Site navigation
nav:
  - Introduzione: 01_introduzione.md
  - Reti logiche combinatorie: 02_reti_logiche_combinatorie.md
  - Reti logiche sequenziali: 03_reti_logiche_sequenziali.md
  - Blocchi costruttivi digitali: 04_blocchi_costruttivi_digitali.md
  - Assembler: 05_assembler.md
  - Microarchitettura: 06_microarchitettura.md
  - Parallelismo: 07_parallelismo.md
  - Gerarchie di memoria: 08_gerarchie_di_memoria.md
  - Dispositivi di IO: 09_dispositivi_IO.md
